### ISSUE TITLE
Create a setup_file.sh to download and setup pendrive instantly!

### ISSUE THREAD

**Issue by hellosaumil** [hellosaumil/PenDrive#3]
Create a _**setup_file.sh**_ to download and setup _PenDrive_ _**instantly**_!

i.e.,

Downloads `pendrive` to home
Adds an alias in `~/.bashrc` or `~/.bash_profile` as `pendrive`

So that User can just write `pendrive` as a command instead of writing cumbersome `./pendrive` to execute.

👍 🍻

**Comment by mayankjobanputra** [comment]
I have added [setup file](https://github.com/hellosaumil/PenDrive/blob/master/setup)

Please check it

**Comment by hellosaumil** [comment]
Thanks @mayankjobanputra it works!

I have modified a bit to add **support for Darwin-like Systems** (i.e., `macOS`).

I think I can **_Close_** It now!
